#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import re
from typing import Iterable

ROOT = pathlib.Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "refs/harfbuzz/test/shape/data/aots/fonts"
TESTS_DIR = ROOT / "refs/harfbuzz/test/shape/data/aots/tests"
OUT_FONTS = ROOT / "src/shape/aots_fonts_gen.mbt"
OUT_CASES = ROOT / "src/shape/aots_cases_gen.mbt"

FEATURE_RE = re.compile(r'--features=\"([^\"]+)\"')
FEATURE_ITEM_RE = re.compile(
    r'^(?P<sign>[+-])?(?P<tag>[A-Za-z0-9]{4})'
    r'(?:\[(?P<range>[0-9:]+)\])?'
    r'(?:=(?P<value>[0-9]+))?$'
)


def chunk_escape(data: bytes, chunk_size: int = 120) -> Iterable[str]:
    hexed = "".join(f"\\x{b:02x}" for b in data)
    for i in range(0, len(hexed), chunk_size):
        yield hexed[i : i + chunk_size]


def bytes_literal_lines(data: bytes) -> list[str]:
    parts = list(chunk_escape(data))
    if not parts:
        return ['b""']
    lines: list[str] = []
    for i, part in enumerate(parts):
        suffix = "+" if i < len(parts) - 1 else ""
        lines.append(f'b"{part}"{suffix}')
    return lines


def emit_fonts() -> None:
    fonts = sorted(FONTS_DIR.glob("*.otf"))
    lines: list[str] = []
    lines.append("///|")
    lines.append("/// Generated by scripts/gen_shape_aots_tests.py; do not edit.")
    lines.append("let aots_fonts : Map[String, Bytes] = {")
    for path in fonts:
        data = path.read_bytes()
        literal_lines = bytes_literal_lines(data)
        first = literal_lines[0]
        lines.append(f'  "{path.name}": {first}')
        for extra in literal_lines[1:]:
            lines.append(f"    {extra}")
        lines[-1] = f"{lines[-1]},"
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn aots_font_bytes(name : String) -> Bytes? {")
    lines.append("  aots_fonts.get(name)")
    lines.append("}")
    lines.append("")
    OUT_FONTS.write_text("\n".join(lines))


def parse_input(codepoints: str) -> list[str]:
    items: list[str] = []
    for part in codepoints.split(","):
        part = part.strip()
        if not part:
            continue
        if not part.startswith("U+"):
            raise ValueError(f"unexpected codepoint: {part}")
        hex_value = part[2:]
        items.append(f"0x{hex_value}")
    return items


def parse_feature_values(feature_str: str, length: int) -> list[int]:
    if feature_str == "test":
        return []
    values = [0 for _ in range(length)]
    for item in feature_str.split(","):
        item = item.strip()
        if not item:
            continue
        m = FEATURE_ITEM_RE.match(item)
        if not m:
            raise ValueError(f"unexpected feature item: {item}")
        tag = m.group("tag")
        if tag != "test":
            raise ValueError(f"unsupported feature tag: {tag}")
        sign = m.group("sign") or "+"
        enabled = sign != "-"
        value = int(m.group("value") or "1")
        if not enabled:
            value = 0
        range_spec = m.group("range")
        if range_spec is None:
            for i in range(length):
                values[i] = value
            continue
        if ":" in range_spec:
            start_s, end_s = range_spec.split(":", 1)
            start = int(start_s) if start_s else 0
            end = int(end_s) if end_s else length
        else:
            start = int(range_spec)
            end = start + 1
        if start < 0:
            start = 0
        if end > length:
            end = length
        for i in range(start, end):
            values[i] = value
    return values


def emit_cases() -> None:
    cases: list[str] = []
    skipped = 0
    for path in sorted(TESTS_DIR.glob("*.tests")):
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("@"):
                continue
            parts = line.split(";")
            if len(parts) < 4:
                continue
            font_path, opts, text, expected = parts[0], parts[1], parts[2], parts[3]
            m = FEATURE_RE.search(opts)
            features = m.group(1) if m else ""
            input_items = parse_input(text)
            feature_values = parse_feature_values(features, len(input_items))
            no_positions = "--no-positions" in opts
            no_advances = "--ned" in opts or "--no-advances" in opts
            font_name = pathlib.Path(font_path).name
            input_literal = ", ".join(input_items)
            expected_literal = expected.replace("\\", "\\\\").replace('"', '\\"')
            feature_literal = ", ".join(str(value) for value in feature_values)
            feature_literal = f"[{feature_literal}]"
            cases.append(
                "  AotsTestCase::{ "
                f'font: "{font_name}", '
                f"input: [{input_literal}], "
                f'expected: "{expected_literal}", '
                f"feature_values: {feature_literal}, "
                f"no_positions: {str(no_positions).lower()}, "
                f"no_advances: {str(no_advances).lower()} "
                "},"
            )
    lines: list[str] = []
    lines.append("///|")
    lines.append("/// Generated by scripts/gen_shape_aots_tests.py; do not edit.")
    lines.append("pub let aots_test_cases : Array[AotsTestCase] = [")
    lines.extend(cases)
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("pub let aots_skipped_cases : Int = ")
    lines.append(f"  {skipped}")
    lines.append("")
    OUT_CASES.write_text("\n".join(lines))


def main() -> None:
    emit_fonts()
    emit_cases()


if __name__ == "__main__":
    main()
