#!/usr/bin/env python3
from __future__ import annotations

import pathlib
from typing import Iterable

ROOT = pathlib.Path(__file__).resolve().parents[1]
TESTS_DIR = ROOT / "refs/harfbuzz/test/subset/data/tests"
FONTS_DIR = ROOT / "refs/harfbuzz/test/subset/data/fonts"
EXPECTED_DIR = ROOT / "refs/harfbuzz/test/subset/data/expected"
OUT = ROOT / "src/subset/subset_data_gen.mbt"

SMOKE = {
    "basics.tests": {
        "fonts": ["Roboto-Regular.abc.ttf"],
        "profiles": ["default.txt"],
        "subsets": ["a", "abc"],
    },
    "cmap.tests": {
        "fonts": ["AdobeBlank-Regular.ttf"],
        "profiles": ["default.txt"],
        "subsets": ["ab", "\ufee6\ufecf"],
    },
}


def chunk_escape(data: bytes, chunk_size: int = 120) -> Iterable[str]:
    hexed = "".join(f"\\x{b:02x}" for b in data)
    for i in range(0, len(hexed), chunk_size):
        yield hexed[i : i + chunk_size]


def bytes_literal_lines(data: bytes) -> list[str]:
    parts = list(chunk_escape(data))
    if not parts:
        return ['b""']
    lines: list[str] = []
    for i, part in enumerate(parts):
        suffix = "+" if i < len(parts) - 1 else ""
        lines.append(f'b"{part}"{suffix}')
    return lines


def parse_suite(definition: str) -> dict[str, list[str]]:
    destinations = {
        "FONTS:": [],
        "PROFILES:": [],
        "SUBSETS:": [],
        "INSTANCES:": [],
        "OPTIONS:": [],
        "IUP_OPTIONS:": [],
    }
    current: list[str] | None = None
    for raw in definition.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line in destinations:
            current = destinations[line]
            continue
        if current is None:
            raise RuntimeError("Failed to parse test suite file.")
        current.append(line)
    return {
        "fonts": destinations["FONTS:"],
        "profiles": destinations["PROFILES:"],
        "subsets": destinations["SUBSETS:"],
        "instances": destinations["INSTANCES:"],
        "options": destinations["OPTIONS:"],
        "iup_options": destinations["IUP_OPTIONS:"],
    }


def unicodes(subset: str) -> str:
    if subset == "*":
        return "all"
    if subset == "no-unicodes":
        return "no-unicodes"
    if subset.startswith("U+"):
        return subset.replace("U+", "")
    return ",".join(f"{ord(c):X}" for c in subset)


def emit() -> None:
    suites: list[tuple[str, dict[str, list[str]]]] = []
    fonts_needed: set[str] = set()
    expected_needed: dict[str, pathlib.Path] = {}

    for suite_name, selection in SMOKE.items():
        path = TESTS_DIR / suite_name
        definition = path.read_text(encoding="utf-8")
        parsed = parse_suite(definition)
        for key in ("fonts", "profiles", "subsets"):
            selected = selection[key]
            parsed[key] = [item for item in parsed[key] if item in selected]
            missing = set(selected) - set(parsed[key])
            if missing:
                raise RuntimeError(f"{suite_name} missing {key}: {sorted(missing)}")
        suites.append((suite_name, parsed))

        suite_base = path.stem
        for font_name in parsed["fonts"]:
            fonts_needed.add(font_name)
            font_base = pathlib.Path(font_name).stem
            font_ext = pathlib.Path(font_name).suffix
            for profile_name in parsed["profiles"]:
                profile_base = pathlib.Path(profile_name).stem
                for subset in parsed["subsets"]:
                    unicode_str = unicodes(subset)
                    expected_name = f"{font_base}.{profile_base}.{unicode_str}{font_ext}"
                    expected_path = EXPECTED_DIR / suite_base / expected_name
                    if not expected_path.exists():
                        raise RuntimeError(f"expected file missing: {expected_path}")
                    key = f"{suite_base}/{expected_name}"
                    expected_needed[key] = expected_path

    lines: list[str] = []
    lines.append("///|")
    lines.append("/// Generated by scripts/gen_subset_smoke_data.py; do not edit.")
    lines.append("pub struct SubsetSmokeSuite {")
    lines.append("  name : String")
    lines.append("  definition : String")
    lines.append("} derive(Show, ToJson)")
    lines.append("")
    lines.append("///|")
    lines.append("pub let subset_smoke_suites : Array[SubsetSmokeSuite] = [")
    for suite_name, parsed in suites:
        def_lines: list[str] = []
        def_lines.append("FONTS:")
        def_lines.extend(parsed["fonts"])
        def_lines.append("")
        def_lines.append("PROFILES:")
        def_lines.extend(parsed["profiles"])
        def_lines.append("")
        def_lines.append("SUBSETS:")
        for subset in parsed["subsets"]:
            if all(ord(ch) < 128 for ch in subset):
                def_lines.append(subset)
            else:
                def_lines.append(",".join(f"U+{ord(ch):04X}" for ch in subset))
        def_lines.append("")
        lines.append("  SubsetSmokeSuite::{")
        lines.append(f'    name: "{suite_name}",')
        lines.append("    definition:")
        lines.append("      (")
        for def_line in def_lines:
            lines.append(f"        #|{def_line}")
        lines.append("      )")
        lines.append("  },")
    lines.append("]")
    lines.append("")

    lines.append("///|")
    lines.append("let subset_smoke_fonts : Map[String, Bytes] = {")
    for font_name in sorted(fonts_needed):
        data = (FONTS_DIR / font_name).read_bytes()
        literal_lines = bytes_literal_lines(data)
        lines.append(f'  "{font_name}": {literal_lines[0]}')
        for extra in literal_lines[1:]:
            lines.append(f"    {extra}")
        lines[-1] = f"{lines[-1]},"
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn subset_smoke_font_bytes(name : String) -> Bytes? {")
    lines.append("  subset_smoke_fonts.get(name)")
    lines.append("}")
    lines.append("")

    lines.append("///|")
    lines.append("let subset_smoke_expected : Map[String, Bytes] = {")
    for key in sorted(expected_needed.keys()):
        data = expected_needed[key].read_bytes()
        literal_lines = bytes_literal_lines(data)
        lines.append(f'  "{key}": {literal_lines[0]}')
        for extra in literal_lines[1:]:
            lines.append(f"    {extra}")
        lines[-1] = f"{lines[-1]},"
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn subset_smoke_expected_bytes(name : String) -> Bytes? {")
    lines.append("  subset_smoke_expected.get(name)")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    emit()


if __name__ == "__main__":
    main()
